# Generated by Django 3.0.6 on 2020-09-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatUsers',
        ),
    ]
