# Generated by Django 3.0.6 on 2020-08-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic_views', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='slug',
        ),
    ]
