# Generated by Django 3.0.6 on 2020-08-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_views', '0002_remove_books_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
